ARG VERSION_NGINEX
ARG VERSION_NGINEX_SUFFIX
ARG VERSION_PNPM
ARG VERSION_TYPESCRIPT
ARG VERSION_TS_NODE

FROM nginx:${VERSION_NGINEX}${VERSION_NGINEX_SUFFIX} as publish
RUN apk add --update npm
RUN npm i -g pnpm@${VERSION_PNPM} typescript@${VERSION_TYPESCRIPT} ts-node@${VERSION_TS_NODE}



COPY nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /startup
COPY package.json startup.ts ./
RUN pnpm i
RUN chmod +x ./startup.ts

ENTRYPOINT ["/startup/startup.ts"]
CMD nginx -g "daemon off;"
