
ARG VERSION_NODEJS
ARG VERSION_NODEJS_SERVE_SUFFIX

FROM node:${VERSION_NODEJS}${VERSION_NODEJS_SERVE_SUFFIXs} as serve

WORKDIR /startup
COPY startup.ts ./
RUN chmod +x ./startup.sh

ENTRYPOINT ["/startup/startup.sh"]
